// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createGreenWord = `-- name: CreateGreenWord :execresult
insert into green_word (name) values ($1)
`

func (q *Queries) CreateGreenWord(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGreenWord, name)
}

const createRedWord = `-- name: CreateRedWord :execresult
insert into red_word (name) values ($1)
`

func (q *Queries) CreateRedWord(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRedWord, name)
}
