// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
)

const createGreenName = `-- name: CreateGreenName :execresult
insert into green_word (name) values ($1)
`

func (q *Queries) CreateGreenName(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGreenName, name)
}

const createRedName = `-- name: CreateRedName :execresult
insert into red_word (name) values ($1)
`

func (q *Queries) CreateRedName(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRedName, name)
}
